name: Build and Zip Chrome Extension

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        shell: bash
        run: pnpm install

      - name: Build Chrome
        run: pnpm build:chrome

      - name: Build Firefox
        run: pnpm build:firefox

      - name: Upload Chrome extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amazon-archive-extension-chrome
          path: dist_chrome

      - name: Upload Firefox extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amazon-archive-extension-firefox
          path: dist_firefox
